=== opengeospatial/ogcapi-sosa/build/annotated/unstable/sosa/properties/observation/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "SOSA Observation",
  "type": "object",
  "properties": {
    "resultTime": {
      "type": "string",
      "format": "date-time",
      "x-jsonld-id": "http://www.w3.org/ns/sosa/resultTime"
    },
    "phenomenonTime": {
      "type": [
        "object",
        "string"
      ],
      "x-jsonld-id": "http://www.w3.org/ns/sosa/phenomenonTime"
    },
    "hasFeatureOfInterest": {
      "type": [
        "object",
        "string"
      ],
      "x-jsonld-id": "http://www.w3.org/ns/sosa/hasFeatureOfInterest",
      "x-jsonld-type": "@id"
    },
    "observedProperty": {
      "type": [
        "object",
        "string"
      ],
      "x-jsonld-id": "http://www.w3.org/ns/sosa/observedProperty"
    },
    "usedProcedure": {
      "type": [
        "object",
        "string"
      ],
      "x-jsonld-id": "http://www.w3.org/ns/sosa/usedProcedure",
      "x-jsonld-type": "@id"
    },
    "madeBySensor": {
      "type": [
        "object",
        "string"
      ],
      "x-jsonld-id": "http://www.w3.org/ns/sosa/madeBySensor",
      "x-jsonld-type": "@id"
    },
    "hasResult": {
      "x-jsonld-id": "http://www.w3.org/ns/sosa/hasResult"
    },
    "hasSimpleResult": {
      "x-jsonld-id": "http://www.w3.org/ns/sosa/hasSimpleResult"
    }
  },
  "oneOf": [
    {
      "required": [
        "hasResult"
      ]
    },
    {
      "required": [
        "hasSimpleResult"
      ]
    }
  ],
  "x-jsonld-prefixes": {
    "sosa": "http://www.w3.org/ns/sosa/",
    "ssn": "http://www.w3.org/ns/ssn/",
    "ssn-system": "http://www.w3.org/ns/ssn/systems/"
  },
  "x-jsonld-extra-terms": {
    "hasSystemProperty": "http://www.w3.org/ns/ssn/systems/hasSystemProperty",
    "Sample": "http://www.w3.org/ns/sosa/Sample",
    "hasSurvivalProperty": "http://www.w3.org/ns/ssn/systems/hasSurvivalProperty",
    "hasOperatingRange": "http://www.w3.org/ns/ssn/systems/hasOperatingRange",
    "actsOnProperty": "http://www.w3.org/ns/sosa/actsOnProperty",
    "isSampleOf": "http://www.w3.org/ns/sosa/isSampleOf",
    "inDeployment": "http://www.w3.org/ns/ssn/inDeployment",
    "detects": "http://www.w3.org/ns/ssn/detects",
    "hasDeployment": "http://www.w3.org/ns/ssn/hasDeployment",
    "hasSystemCapability": "http://www.w3.org/ns/ssn/systems/hasSystemCapability",
    "qualityOfObservation": "http://www.w3.org/ns/ssn/systems/qualityOfObservation",
    "hosts": "http://www.w3.org/ns/sosa/hosts",
    "wasOriginatedBy": "http://www.w3.org/ns/ssn/wasOriginatedBy",
    "hasSample": "http://www.w3.org/ns/sosa/hasSample",
    "deployedSystem": "http://www.w3.org/ns/ssn/deployedSystem",
    "madeSampling": "http://www.w3.org/ns/sosa/madeSampling",
    "hasSubSystem": "http://www.w3.org/ns/ssn/hasSubSystem",
    "madeObservation": "http://www.w3.org/ns/sosa/madeObservation",
    "madeActuation": "http://www.w3.org/ns/sosa/madeActuation",
    "hasOperatingProperty": "http://www.w3.org/ns/ssn/systems/hasOperatingProperty",
    "isPropertyOf": "http://www.w3.org/ns/ssn/isPropertyOf",
    "Observation": "http://www.w3.org/ns/sosa/Observation",
    "deployedOnPlatform": "http://www.w3.org/ns/ssn/deployedOnPlatform",
    "isActedOnBy": "http://www.w3.org/ns/sosa/isActedOnBy",
    "hasOutput": "http://www.w3.org/ns/ssn/hasOutput",
    "isFeatureOfInterestOf": "http://www.w3.org/ns/sosa/isFeatureOfInterestOf",
    "isObservedBy": "http://www.w3.org/ns/sosa/isObservedBy",
    "hasSimpleResult": "http://www.w3.org/ns/sosa/hasSimpleResult",
    "hasResult": "http://www.w3.org/ns/sosa/hasResult",
    "isProxyFor": "http://www.w3.org/ns/ssn/isProxyFor",
    "hasSurvivalRange": "http://www.w3.org/ns/ssn/systems/hasSurvivalRange",
    "hasProperty": "http://www.w3.org/ns/ssn/hasProperty",
    "hasInput": "http://www.w3.org/ns/ssn/hasInput",
    "forProperty": "http://www.w3.org/ns/ssn/forProperty",
    "hasMember": "http://www.w3.org/ns/sosa/hasMember",
    "madeByActuator": "http://www.w3.org/ns/sosa/madeByActuator",
    "madeBySampler": "http://www.w3.org/ns/sosa/madeBySampler",
    "inCondition": "http://www.w3.org/ns/ssn/systems/inCondition",
    "features": "http://www.w3.org/ns/sosa/hasMember",
    "implementedBy": "http://www.w3.org/ns/ssn/implementedBy",
    "isResultOf": "http://www.w3.org/ns/sosa/isResultOf",
    "observes": "http://www.w3.org/ns/sosa/observes",
    "implements": "http://www.w3.org/ns/ssn/implements",
    "isHostedBy": "http://www.w3.org/ns/sosa/isHostedBy"
  }
}

=== opengeospatial/ogcapi-sosa/build/annotated/features/observation/example3.json
{
  "resultTime": "1962-07-11T10:01:18.0Z",
  "hasFeatureOfInterest": {
    "nisi0": 28926077.88594033
  },
  "hasResult": {},
  "madeBySensor": {
    "consectetur_f6": "veniam enim",
    "pariatur_5b": 96239060
  },
  "observedProperty": {
    "nisi_4f": false
  },
  "phenomenonTime": "velit Ut adipisicing sed",
  "usedProcedure": "esse mollit"
}
